openapi: 3.1.0
info:
  title: Factory Floor PWA API
  version: v1
  description: |
    Versioned API contract. Core expectations:
      - JWT/OAuth authentication
      - Role-based access control
      - Audit logging
      - Strict typing of request/response shapes
servers:
  - url: https://api.example.com/v1
paths:
  /license/verify:
    get:
      summary: Verify a licence token
      parameters:
        - in: query
          name: session_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Valid licence
          content:
            application/json:
              schema:
                type: object
                properties:
                  licenceToken:
                    type: string
        '401':
          description: Invalid or expired
  /incident:
    post:
      summary: Submit a non-conformity incident
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                severity:
                  type: string
                  enum: [Low, Medium, High]
                reporter:
                  type: string
                shiftCode:
                  type: string
      responses:
        '201':
          description: Created
        '400':
          description: Validation error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
